config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'notices#index'
  resources :notices do
    resources :comments
  end

  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :notice
  belongs_to :user
end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: {:message => "El titulo es requerido"}
  validates :body, presence: {:message => "El titulo es requerido"}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notices
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def to_s
    "#{email}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_notice, only: [:create, :destroy]

  def create
    @comment = @notice.comments.create(comment_params.merge(user_id: current_user.id))
    redirect_to @notice
  end

  def destroy
    @comment = @notice.comments.find(params[:id])
    @comment.destroy
    redirect_to @notice
  end

  private
    def set_notice
      @notice = Notice.find(params[:notice_id])
    end

    def comment_params
      params.require(:comment).permit(:name, :body, :notice_id)
    end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all.order('created_at DESC')
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = current_user.notices.build
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = current_user.notices.build(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:title, :body)
    end

    def correct_user
      @notice = current_user.notices.find_by(id: params[:id])
      redirect_to notices_path, notice: "No esta autorizado para editar este articulo" if @notice.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/comments/_comment.haml
%article
  %h3= comment.user
  %p
    =comment.body
    -if user_signed_in?
      -if current_user.id == comment.user_id
        %br
        =link_to 'Eliminar', [comment.notice, comment], method: :delete, data: {confirm: '¿Seguro desea eliminar su comentario?'}

app/views/comments/_form.html.haml
= form_for([@notice, @notice.comments.build], remote: true) do |f|

  .form-group
    = f.label 'Comentario'
    = f.text_area :body, class: 'form-control'

  .actions
    = f.submit 'Enviar comentario', class: 'btn btn-info'

app/views/layouts/_menu.html.haml
.container-fluid#menu-top
  .row
    .col
      %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
        = link_to 'NewsWeb', notices_path, class: 'navbar-brand'
        %ul.navbar-nav.ml-auto
          %li.nav-item
            = link_to 'Todas las noticias', notices_path, class: 'nav-link'
          %li.nav-item
            = link_to 'Crear Noticia', new_notice_path, class: 'nav-link'
          %li.nav-item.dropdown
            -if user_signed_in?
              %a.nav-link.dropdown-toggle{'data-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false'} #{current_user.email.to_s}
              .dropdown-menu
                =link_to "Editar cuenta",  edit_user_registration_path(current_user.id), class: "dropdown-item"
                = link_to "cerrar sesión",  destroy_user_session_path, method: :delete, class: "dropdown-item"
            - else
              %a.nav-link.dropdown-toggle{'data-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false'} Gestión de usuario
              .dropdown-menu
                =link_to "Iniciar sesion", new_user_session_path, class: "dropdown-item"
                =link_to "Crear cuenta",  new_user_registration_path, class: "dropdown-item"

app/views/layouts/_messages.html.haml
- if notice
  .notice-alert
    %section.alert.alert-success.alert-dismissible.fade.show{'role' => 'alert'}
      = notice
      %button.close{ 'type' => 'button', 'data-dismiss' => 'alert', 'aria-label' => 'Close'}
        %span{'aria-hidden' => 'true'} &times;

- if alert
  .notice-alert
    %section.alert.alert-danger.alert-dismissible.fade.show{'role' => 'alert'}
      = alert
      %button.close{ 'type' => 'button', 'data-dismiss' => 'alert', 'aria-label' => 'Close'}
        %span{'aria-hidden' => 'true'} &times;

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Newsweb
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/menu'
    = render partial: 'layouts/messages'
    .container.mt-4
      = yield

app/views/notices/_form.html.haml
= form_with(model: notice, local: true) do |form|
  - if @notice.errors.any?
    #error_explanation
      %h2
        = pluralize(notice.errors.count, "error")
        *No se puede guardar su noticia:
      %ul
        - @notice.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label 'Titulo'
    = form.text_field :title, class: 'form-control'
  .form-group
    = form.label 'Noticia'
    = form.text_area :body, class: 'form-control', :rows => 8
  .actions
    -if @notice.new_record?
      = form.submit 'Crear noticia', class: 'btn btn-secondary'
    -else
      = form.submit 'Actualizar noticia', class: 'btn btn-secondary'
    = link_to 'Cancelar', notices_path, class: 'btn btn-info'

app/views/notices/edit.html.haml
%h1 Editing Notice
= render 'form', notice: @notice
= link_to 'Show', @notice
|
= link_to 'Back', notices_path

app/views/notices/index.html.haml
%p#notice= notice
%h1 Últimas Noticias
- @notices.each do |notice|
  .list-group

    %h2= link_to notice.title, notice
    %p= notice.body.truncate_words(60)
  %hr
%br/
= link_to 'Crear noticia', new_notice_path, class: 'btn btn-secondary'

app/views/notices/new.html.haml
%h1 New Notice
= render 'form', notice: @notice

app/views/notices/show.html.haml
%h1= @notice.title
%p= @notice.body

-if user_signed_in?
  -if current_user.id == @notice.user_id
    .action-notice
      = link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' }
      = link_to 'Edit', edit_notice_path(@notice)

%hr
-if user_signed_in?
  %h5 Deje su comentario:
  = render 'comments/form'
-else
  .alert.alert-info
    Registrate para comentar esta noticia.
%hr
#comments.mt-2
  %p #{@notice.comments.count} Comentarios
  =render @notice.comments

= link_to 'Todas las noticias', notices_path, class: 'btn btn-secondary'